# General  
finetune: True
partial_train: null

# Traning 
epochs: 200
batch_size: 4 
lr_backbone: 0.0001
lr_head: 0.001
weight_decay: 0.1
lr_decay: 0.99

# Model
model_version: class
maxlen: 41
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True
num_joints: 17
hidden_dim: 2048
dropout_ratio: 0.5

# Data
dataset: volleyhrnet
data_split: xsub
clip_len: 41
action_classes: 8

# Augmentation
random_move: True
scale_range_train: [1, 3]
scale_range_test: [2, 2]